### ISSUE TITLE
Missing import { marketComponent, }

### ISSUE THREAD

**Issue by karstenjakobsen** [Reiryoku-Technologies/Mida#89]
Hi

Im reading the docs:

`https://github.com/Reiryoku-Technologies/Mida#market-components` 

and

`https://www.mida.org/posts/reactive-programming-in-financial-markets/#component-structure`

But it doesn't seem to be implemented in the `2022.5.0` release - am I missing something?

**Comment by karstenjakobsen** [comment]
On another note - I would love to help you out with setting up some kind og build pipeline with e.g `github-actions` . Let me know if you're interested!

**Comment by Vasile-Peste** [comment]
Hello, we are sorry for the inconvenience but the readme is not synced with the actual release but with the next one since most changes have been merged in master and we are preparing for a new release.
In the meanwhile if you want to try: you can pull master, build it and use the APIs described in the document.
We took note of this issue and we will make sure that will not happen again, so we are going to update the README only after the actual release.

If you want to contribute feel free to reach us on [Telegram](https://t.me/joinmida) or [Discord](https://discord.gg/cKyWTUsr3q).

Thank you!
